//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PhieuThu_EF04.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QL_PhieuThu_EF04.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don vi tinh khong qua 10 ky tu!.
        /// </summary>
        internal static string ErrDonViTinh {
            get {
                return ResourceManager.GetString("ErrDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ErrGhiChu {
            get {
                return ResourceManager.GetString("ErrGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap sai!.
        /// </summary>
        internal static string ErrGiaBan {
            get {
                return ResourceManager.GetString("ErrGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma loai nguyen lieu phai la so nguyen!.
        /// </summary>
        internal static string ErrLoaiNguyenLieuID {
            get {
                return ResourceManager.GetString("ErrLoaiNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay lap phieu phai la kieu ngay thang !.
        /// </summary>
        internal static string ErrNgayLap {
            get {
                return ResourceManager.GetString("ErrNgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nguyen lieu phai la so nguyen!.
        /// </summary>
        internal static string ErrNguyenLieuID {
            get {
                return ResourceManager.GetString("ErrNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma phieu thu phai la so nguyen!.
        /// </summary>
        internal static string ErrPhieuThuID {
            get {
                return ResourceManager.GetString("ErrPhieuThuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong ban phai la so nguyen!.
        /// </summary>
        internal static string ErrSoLuongBan {
            get {
                return ResourceManager.GetString("ErrSoLuongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong phai la so nguyen!.
        /// </summary>
        internal static string ErrSoLuongKho {
            get {
                return ResourceManager.GetString("ErrSoLuongKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nguyen lieu khong duoc qua 20 ky tu!.
        /// </summary>
        internal static string ErrTenNguyenLieu {
            get {
                return ResourceManager.GetString("ErrTenNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nhan vien khong qua 20 ky tu !.
        /// </summary>
        internal static string ErrTenNhanVienLapPhieu {
            get {
                return ResourceManager.GetString("ErrTenNhanVienLapPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap chi tiet phieu thu.
        /// </summary>
        internal static string InpChiTietPhieuThu {
            get {
                return ResourceManager.GetString("InpChiTietPhieuThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap don vi tinh: .
        /// </summary>
        internal static string InpDonViTinh {
            get {
                return ResourceManager.GetString("InpDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu: .
        /// </summary>
        internal static string InpGhiChu {
            get {
                return ResourceManager.GetString("InpGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gia ban: .
        /// </summary>
        internal static string InpGiaBan {
            get {
                return ResourceManager.GetString("InpGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma loai nguyen lieu: .
        /// </summary>
        internal static string InpLoaiNguyenLieuID {
            get {
                return ResourceManager.GetString("InpLoaiNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay lap phieu:.
        /// </summary>
        internal static string InpNgayLap {
            get {
                return ResourceManager.GetString("InpNgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma nguyen lieu: .
        /// </summary>
        internal static string InpNguyenLieuID {
            get {
                return ResourceManager.GetString("InpNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma phieu thu: .
        /// </summary>
        internal static string InpPhieuThuID {
            get {
                return ResourceManager.GetString("InpPhieuThuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong ban: .
        /// </summary>
        internal static string InpSoLuongBan {
            get {
                return ResourceManager.GetString("InpSoLuongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong co trong kho: .
        /// </summary>
        internal static string InpSoLuongKho {
            get {
                return ResourceManager.GetString("InpSoLuongKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten nguyen lieu: .
        /// </summary>
        internal static string InpTenNguyenLieu {
            get {
                return ResourceManager.GetString("InpTenNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten nhan vien: .
        /// </summary>
        internal static string InpTenNhanVienLapPhieu {
            get {
                return ResourceManager.GetString("InpTenNhanVienLapPhieu", resourceCulture);
            }
        }
    }
}
