//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanVienEF.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLNhanVienEF.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai la 1 chuoi!.
        /// </summary>
        internal static string errorDiaChi {
            get {
                return ResourceManager.GetString("errorDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma du an phai la so nguyen!.
        /// </summary>
        internal static string errorDuAnId {
            get {
                return ResourceManager.GetString("errorDuAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai la 1 chuoi!.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai la 1 chuoi!.
        /// </summary>
        internal static string errorGhiChu {
            get {
                return ResourceManager.GetString("errorGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai la so nguyen!.
        /// </summary>
        internal static string errorHeSoLuong {
            get {
                return ResourceManager.GetString("errorHeSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong duoc qua 20 ky tu va co it nhat 2 tu!.
        /// </summary>
        internal static string errorHoten {
            get {
                return ResourceManager.GetString("errorHoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phai la 1 chuoi!.
        /// </summary>
        internal static string errorMota {
            get {
                return ResourceManager.GetString("errorMota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nhan vien phai la so nguyen!.
        /// </summary>
        internal static string errorNhanVienId {
            get {
                return ResourceManager.GetString("errorNhanVienId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai phai la so!.
        /// </summary>
        internal static string errorSdt {
            get {
                return ResourceManager.GetString("errorSdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So gio lam phai la so nguyen!.
        /// </summary>
        internal static string errorSoGioLam {
            get {
                return ResourceManager.GetString("errorSoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten du an khong duoc qua 10 ky tu!.
        /// </summary>
        internal static string errorTenDuAn {
            get {
                return ResourceManager.GetString("errorTenDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap dia chi:.
        /// </summary>
        internal static string inputDiaChi {
            get {
                return ResourceManager.GetString("inputDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma du an:.
        /// </summary>
        internal static string inputDuAnId {
            get {
                return ResourceManager.GetString("inputDuAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap Email:.
        /// </summary>
        internal static string inputEmail {
            get {
                return ResourceManager.GetString("inputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu:.
        /// </summary>
        internal static string inputGhiChu {
            get {
                return ResourceManager.GetString("inputGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap he so luong:.
        /// </summary>
        internal static string inputHeSoLuong {
            get {
                return ResourceManager.GetString("inputHeSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten nhan vien:.
        /// </summary>
        internal static string inputHoTen {
            get {
                return ResourceManager.GetString("inputHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap mo ta:.
        /// </summary>
        internal static string inputMoTa {
            get {
                return ResourceManager.GetString("inputMoTa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma nhan vien: .
        /// </summary>
        internal static string inputNhanVienId {
            get {
                return ResourceManager.GetString("inputNhanVienId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so dien thoai:.
        /// </summary>
        internal static string inputSdt {
            get {
                return ResourceManager.GetString("inputSdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so gio lam cho nhan vien:.
        /// </summary>
        internal static string inputSoGioLam {
            get {
                return ResourceManager.GetString("inputSoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten du an:.
        /// </summary>
        internal static string inputTenDuAn {
            get {
                return ResourceManager.GetString("inputTenDuAn", resourceCulture);
            }
        }
    }
}
