// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_KhoaHoc_EF03;

namespace QL_KhoaHoc_EF03.Migrations
{
    [DbContext(typeof(QLKhoaHocDbContext))]
    [Migration("20210402090920_intitial")]
    partial class intitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.HocVien", b =>
                {
                    b.Property<int>("HocVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HocVienID");

                    b.HasIndex("KhoaHocID");

                    b.ToTable("hocViens");
                });

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HocPhi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhoaHocID");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.NgayHoc", b =>
                {
                    b.Property<int>("NgayHocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NgayHocID");

                    b.HasIndex("KhoaHocID");

                    b.ToTable("ngayHocs");
                });

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.HocVien", b =>
                {
                    b.HasOne("QL_KhoaHoc_EF03.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.NgayHoc", b =>
                {
                    b.HasOne("QL_KhoaHoc_EF03.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("NgayHocs")
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QL_KhoaHoc_EF03.Entities.KhoaHoc", b =>
                {
                    b.Navigation("HocViens");

                    b.Navigation("NgayHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
