// <auto-generated />
using EFC_02;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFC_02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210715072620_intitial")]
    partial class intitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFC_02.Entities.CongThuc", b =>
                {
                    b.Property<int>("CongThucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonAnID")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("CongThucID");

                    b.HasIndex("MonAnID");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("congThucs");
                });

            modelBuilder.Entity("EFC_02.Entities.LoaiMonAn", b =>
                {
                    b.Property<int>("LoaiMonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiMonAnID");

                    b.ToTable("loaiMonAns");
                });

            modelBuilder.Entity("EFC_02.Entities.MonAn", b =>
                {
                    b.Property<int>("MonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiMonAnID")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonAnID");

                    b.HasIndex("LoaiMonAnID");

                    b.ToTable("monAns");
                });

            modelBuilder.Entity("EFC_02.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenLieuID");

                    b.ToTable("nguyenLieus");
                });

            modelBuilder.Entity("EFC_02.Entities.CongThuc", b =>
                {
                    b.HasOne("EFC_02.Entities.MonAn", "MonAn")
                        .WithMany("CongThucs")
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC_02.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("CongThucs")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("EFC_02.Entities.MonAn", b =>
                {
                    b.HasOne("EFC_02.Entities.LoaiMonAn", "LoaiMonAn")
                        .WithMany()
                        .HasForeignKey("LoaiMonAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMonAn");
                });

            modelBuilder.Entity("EFC_02.Entities.MonAn", b =>
                {
                    b.Navigation("CongThucs");
                });

            modelBuilder.Entity("EFC_02.Entities.NguyenLieu", b =>
                {
                    b.Navigation("CongThucs");
                });
#pragma warning restore 612, 618
        }
    }
}
