//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_MonAn_EF_05.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QL_MonAn_EF_05.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string errCachLam {
            get {
                return ResourceManager.GetString("errCachLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string errCongThuc {
            get {
                return ResourceManager.GetString("errCongThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string errDonViTinh {
            get {
                return ResourceManager.GetString("errDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban phai la so !.
        /// </summary>
        internal static string errGiaBan {
            get {
                return ResourceManager.GetString("errGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string errGioiThieu {
            get {
                return ResourceManager.GetString("errGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loai mon an ID phai la so nguyen !.
        /// </summary>
        internal static string errLoaiMonAnID {
            get {
                return ResourceManager.GetString("errLoaiMonAnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon an ID phai la so nguyen !.
        /// </summary>
        internal static string errMonAnID {
            get {
                return ResourceManager.GetString("errMonAnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyen lieu ID la so nguyen !.
        /// </summary>
        internal static string errNguyenLieuID {
            get {
                return ResourceManager.GetString("errNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong phai la so nguyen !.
        /// </summary>
        internal static string errSoLuong {
            get {
                return ResourceManager.GetString("errSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten mon an khong duoc qua 20 ky tu !.
        /// </summary>
        internal static string errTenMon {
            get {
                return ResourceManager.GetString("errTenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string inpCachLam {
            get {
                return ResourceManager.GetString("inpCachLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap cong thuc.
        /// </summary>
        internal static string inpCongThuc {
            get {
                return ResourceManager.GetString("inpCongThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap don vi tinh: .
        /// </summary>
        internal static string inpDonViTinh {
            get {
                return ResourceManager.GetString("inpDonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gia ban: .
        /// </summary>
        internal static string inpGiaBan {
            get {
                return ResourceManager.GetString("inpGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gioi thieu mon an: .
        /// </summary>
        internal static string inpGioiThieu {
            get {
                return ResourceManager.GetString("inpGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap loai mon an ID: .
        /// </summary>
        internal static string inpLoaiMonAnID {
            get {
                return ResourceManager.GetString("inpLoaiMonAnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap mon an ID: .
        /// </summary>
        internal static string inpMonAnID {
            get {
                return ResourceManager.GetString("inpMonAnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nguyen lieu ID: .
        /// </summary>
        internal static string inpNguyenLieuID {
            get {
                return ResourceManager.GetString("inpNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong: .
        /// </summary>
        internal static string inpSoLuong {
            get {
                return ResourceManager.GetString("inpSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten mon an: .
        /// </summary>
        internal static string inpTenMon {
            get {
                return ResourceManager.GetString("inpTenMon", resourceCulture);
            }
        }
    }
}
